apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: chibisafe
data:
  nginx.conf: |
    user  nginx;
    worker_processes auto;
    events {}
    http{
      include      mime.types;
      include      /etc/nginx/sites-enabled/*.conf;
      sendfile        on;
      keepalive_timeout 65;
      default_type  application/octet-stream;
    }

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-chibisafe
  namespace: chibisafe
data:
  chibisafe.conf: |
    server {
        listen 80;
        listen [::]:80;
        server_name chibisafe.wololoaeyoyo.com;
        client_max_body_size 1024M; # Change this to the max file size you want to allow

        root /app/uploads;

        location ^~ /api/ {
            add_header Access-Control-Allow-Origin *;          
            proxy_pass http://chibisafe-backend.chibisafe.svc.cluster.local:8000;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
          
        }

        location ^~ /docs/ {
          try_files $uri @docs;
        }

        location /thumbs/ {
            alias /app/uploads/;
        }    

        location @docs {
            add_header Access-Control-Allow-Origin *;
            proxy_pass http://chibisafe-backend.chibisafe.svc.cluster.local:8000;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location / {
            try_files $uri @frontend;
        }

        location @frontend {
            add_header Access-Control-Allow-Origin *;            
            proxy_pass http://chibisafe.chibisafe.svc.cluster.local:8001;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
