apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: chibisafe-backend-ingress
  namespace: chibisafe
  annotations:
    kubernetes.io/ingress.class: cloudflare-tunnel
spec:
  rules:
    - host: chibisafe-backend.wololoaeyoyo.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: chibisafe-backend
                port:
                  number: 8000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: chibiproxy-ingress
  namespace: chibisafe
  annotations:
    kubernetes.io/ingress.class: cloudflare-tunnel
spec:
  rules:  
    - host: chibisafe.wololoaeyoyo.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nginx-chibisafe
                port:
                  number: 80