apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: loki-deployment
  namespace: loki
spec:
  targetNamespace: grafana-helm
  chart:
    spec:
      chart: loki
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: grafana-helm
      version: 6.49.0
  interval: 1m0s
  valuesFrom:
    - kind: ConfigMap
      name: loki-configmap