apiVersion: apps/v1
kind: Deployment
metadata:
  name: k6-trace-generator
  namespace: tempo
  labels:
    app: k6-trace-generator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k6-trace-generator
  template:
    metadata:
      labels:
        app: k6-trace-generator
    spec:
      containers:
        - name: k6-tracing
          image: ghcr.io/grafana/xk6-client-tracing:v0.0.7
          env:
            - name: ENDPOINT
              value: "alloy-k8s-monitoring-alloy-receiver.svc.cluster.local:4317"  # Send spans directly to Alloy via OTLP/gRPC
          resources:
            limits:
              cpu: 200m
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 128Mi
      restartPolicy: Always