apiVersion: v1
kind: Service
metadata:
  name: k6-trace-generator
  namespace: monitoring
spec:
  selector:
    app: k6-trace-generator
  ports:
    - port: 8080
      targetPort: 8080
      name: http
  type: loadBalancer