apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: default
  labels:
    app: nginx
spec:
  replicas: 3
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        env:
          - name: admin
            valueFrom:
              secretKeyRef:
                name: nginx-password
                key: admin
          - name: acceder
            valueFrom:
              secretKeyRef:
                name: nginx-password
                key: acceder
        volumeMounts:
          - name: nginx-config
            mountPath: /etc/nginx/nginx.conf
            subPath: nginx.conf

          - name: nginx-longhorn
            mountPath: /etc/nginx/sites-enabled/longhorn.conf
            subPath: longhorn.conf
          
          - name: nginx-password
            mountPath: /etc/nginx/pass.txt
            subPath: pass.txt
      volumes:
        - name: nginx-config
          configMap:
            name: nginx-config
            items:
              - key: nginx.conf
                path: nginx.conf

        - name: nginx-longhorn
          configMap:
            name: nginx-longhorn
            items:
              - key: longhorn.conf
                path: longhorn.conf
        
        - name: nginx-password
          secret:
            secretName: nginx-password
            items:
              - key: pass.txt
                path: pass.txt