#source https://grafana.com/docs/tempo/latest/collect/logs-in-kubernetes/
apiVersion: v1
kind: ConfigMap
metadata:
  name: minecraft-configmap
  namespace: minecraft
data:
  values.yaml: |
    minecraftServer:
      eula: "true"
      version: LATEST
      gameMode: survival
      motd: "Mariguanos y periqueros!!"
      onlineMode: true
      memory: 4g
    resources:
      requests:
        memory: 2Gi
        cpu: 1
      limits:
        memory: 4Gi
        cpu: 6
    nodeSelector:
      kubernetes.io/hostname: worker-1
    persistence:
      annotations: {}
      dataDir:
        enabled: true
        Size: 6Gi