apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: grafana-system
  namespace: flux-system
spec:
  interval: 1m
  path: ./lgtm
  prune: true
  timeout: 1m
  sourceRef:
    kind: GitRepository
    name: flux-system
---