apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: minecraft-kustomization
  namespace: flux-system
spec:
  interval: 1m
  path: ./minecraft
  prune: true
  timeout: 2m
  sourceRef:
    kind: GitRepository
    name: flux-system
---